language: python
python:
    - "3.6"

install:
    - pip install codecov
    - pip install -U pytest
    - pip install -U pytest-cov
    - pip install -e .[test]

script:
    - pytest tests --cov=rcv --cov-report term-missing --doctest-modules

# Push the results back to codecov
after_success:
    - codecov
